name: scripts
channels:
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - intel-openmp
  - libcxx
  - libedit
  - libffi
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pip
  - python
  - python-dateutil
  - pytz
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
