name: scripts
channels:
    - defaults
dependencies:
    - blas=1.0
    - ca-certificates=2021.1.19
    - certifi=2020.12.5
    - cloudpickle=1.6.0
    - cycler=0.10.0
    - cytoolz=0.11.0
    - dask-core=2021.3.0
    - decorator=4.4.2
    - freetype=2.10.4
    - imageio=2.9.0
    - intel-openmp=2019.4
    - jpeg=9b
    - kiwisolver=1.3.1
    - lcms2=2.11
    - libcxx=10.0.0
    - libedit=3.1.20191231
    - libffi=3.3
    - libgfortran=3.0.1
    - libpng=1.6.37
    - libtiff=4.2.0
    - libwebp-base=1.2.0
    - llvm-openmp=10.0.0
    - lz4-c=1.9.3
    - matplotlib-base=3.3.4
    - mkl=2019.4
    - mkl-service=2.3.0
    - mkl_fft=1.2.0
    - mkl_random=1.1.1
    - ncurses=6.2
    - networkx=2.5
    - numpy=1.19.2
    - numpy-base=1.19.2
    - olefile=0.46
    - openssl=1.1.1j
    - pandas=1.1.5
    - pillow=8.1.2
    - pip=20.3.3
    - pyparsing=2.4.7
    - python=3.8.5
    - python-dateutil=2.8.1
    - pytz=2020.5
    - pywavelets=1.1.1
    - pyyaml=5.4.1
    - readline=8.0
    - scikit-image=0.17.2
    - scipy=1.6.1
    - setuptools=51.0.0
    - six=1.15.0
    - sqlite=3.33.0
    - tifffile=2020.10.1
    - tk=8.6.10
    - toolz=0.11.1
    - tornado=6.1
    - wheel=0.36.2
    - xz=5.2.5
    - yaml=0.2.5
    - zlib=1.2.11
    - zstd=1.4.5
